import html2canvas from "html2canvas-pro";
import jsPDF from "jspdf";

// Store raw notes for PDF generation
let storedNotes = "";
let storedDiagramUrl = "";

export const setNotesForPDF = (notes: string, diagramUrl?: string) => {
  storedNotes = notes;
  storedDiagramUrl = diagramUrl || "";
};

// Wait for fonts to be ready
const waitForFonts = async (): Promise<void> => {
  if (document.fonts && document.fonts.ready) {
    await document.fonts.ready;
  }
  await new Promise((resolve) => setTimeout(resolve, 500));
};

export const downloadPDF = async () => {
  // Try to get notes from storage or from DOM
  const notesElement =
    document.getElementById("pdf-content") ||
    document.getElementById("notes-container");

  if (!notesElement && !storedNotes) {
    alert("Notes container not found!");
    return;
  }

  // Get diagram URL from DOM if available
  const diagramImg = notesElement?.querySelector("img[crossorigin]");
  const diagramUrl = diagramImg 
    ? (diagramImg.getAttribute("src") || "") 
    : storedDiagramUrl;

  // Use stored notes or extract from DOM
  const notesText = storedNotes || (notesElement?.innerText || "");

  // Helper function to cleanup PDF container
  const cleanupContainer = (container: HTMLDivElement) => {
    if (container && container.parentNode) {
      document.body.removeChild(container);
    }
  };

  try {
    console.log("Starting PDF generation with notes length:", notesText.length);

    // Wait for fonts
    await waitForFonts();

    // Create a clean, off-screen container for PDF rendering
    // Position it off-screen to prevent it from being visible to the user
    const pdfContainer = document.createElement("div");
    pdfContainer.style.cssText = `
      position: fixed;
      top: -10000px;
      left: -10000px;
      width: 794px;
      min-height: 1123px;
      padding: 50px 60px;
      margin: 0;
      background-color: #fffdf7;
      background-image: repeating-linear-gradient(transparent, transparent 31px, #dbeafe 32px);
      font-family: 'Caveat', cursive;
      font-size: 26px;
      line-height: 32px;
      color: #1a1a2e;
      box-sizing: border-box;
      z-index: -1;
      visibility: visible;
      opacity: 1;
    `;

    // Add header
    const headerHtml = `
      <div style="text-align: center; margin-bottom: 30px; padding-bottom: 15px; border-bottom: 3px solid #3b82f6;">
        <h1 style="font-size: 42px; color: #1d4ed8; margin: 0; font-weight: 700; font-family: 'Caveat', cursive;">📖 Study Notes</h1>
        <p style="font-size: 18px; color: #64748b; margin: 5px 0 0 0; font-family: 'Caveat', cursive;">Generated by Lisa AI Assistant</p>
        <p style="font-size: 16px; color: #94a3b8; margin: 5px 0 0 0; font-family: 'Caveat', cursive;">${new Date().toLocaleDateString("en-IN", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })}</p>
      </div>
    `;

    // Render markdown to HTML with handwritten styling
    const renderMarkdownToHtml = (markdown: string): string => {
      let html = markdown;

      // Escape HTML first
      html = html.replace(/&/g, "&")
                 .replace(/</g, "<")
                 .replace(/>/g, ">");

      // Headers (must be first)
      html = html.replace(/^### (.+)$/gm, '<h3 style="font-size: 30px; color: #166534; margin: 20px 0 10px 0; font-weight: 600; font-family: \'Caveat\', cursive;">$1</h3>');
      html = html.replace(/^## (.+)$/gm, '<h2 style="font-size: 34px; color: #dc2626; margin: 25px 0 12px 0; font-weight: 700; background: #fef2f2; padding: 8px 12px; border-radius: 8px; font-family: \'Caveat\', cursive;">$1</h2>');
      html = html.replace(/^# (.+)$/gm, '<h1 style="font-size: 38px; color: #1d4ed8; margin: 30px 0 15px 0; font-weight: 700; border-bottom: 2px solid #93c5fd; padding-bottom: 8px; font-family: \'Caveat\', cursive;">$1</h1>');

      // Bold and italic
      html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong style="font-weight: 700; color: #7c3aed;"><em>$1</em></strong>');
      html = html.replace(/\*\*(.+?)\*\*/g, '<strong style="font-weight: 700; color: #2563eb;">$1</strong>');
      html = html.replace(/\*(.+?)\*/g, '<em style="font-style: italic; color: #7c3aed;">$1</em>');

      // Bullet lists
      html = html.replace(/^\s*[-*+]\s+(.+)$/gm, '<li style="margin: 4px 0; padding-left: 5px; list-style-type: disc;">$1</li>');

      // Numbered lists
      html = html.replace(/^\s*\d+\.\s+(.+)$/gm, '<li style="margin: 4px 0; padding-left: 5px; list-style-type: decimal;">$1</li>');

      // Wrap consecutive li elements
      html = html.replace(/((<li[^>]*>.*<\/li>\n?)+)/g, '<ul style="margin: 10px 0; padding-left: 35px;">$1</ul>');

      // Inline code
      html = html.replace(/`([^`]+)`/g, '<code style="background: #f1f5f9; padding: 2px 8px; border-radius: 4px; font-family: monospace; font-size: 22px; color: #dc2626;">$1</code>');

      // Code blocks
      html = html.replace(/```([\s\S]*?)```/g, '<pre style="background: #f8fafc; padding: 15px; border-radius: 8px; overflow-x: auto; margin: 15px 0; border: 1px solid #e2e8f0;"><code style="font-family: monospace; font-size: 22px; line-height: 1.5;">$1</code></pre>');

      // Blockquotes
      html = html.replace(/>\s*(.+)$/gm, '<blockquote style="border-left: 4px solid #3b82f6; background: #eff6ff; padding: 10px 15px; margin: 10px 0; border-radius: 0 8px 8px 0; font-style: italic;">$1</blockquote>');

      // Paragraphs - wrap remaining text lines
      const lines = html.split("\n");
      const processed: string[] = [];
      
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed === "") {
          processed.push("<br/>");
        } else if (
          trimmed.startsWith("<h") || 
          trimmed.startsWith("<u") || 
          trimmed.startsWith("<o") || 
          trimmed.startsWith("<l") ||
          trimmed.startsWith("<b") ||
          trimmed.startsWith("<p") ||
          trimmed.startsWith("<pre") ||
          trimmed.startsWith("<code") ||
          trimmed.startsWith("<blockquote") ||
          trimmed.startsWith("<br") ||
          trimmed.startsWith("</")
        ) {
          processed.push(trimmed);
        } else {
          processed.push(`<p style="margin: 6px 0; color: #334155; font-family: 'Caveat', cursive;">${trimmed}</p>`);
        }
      }

      return processed.join("\n");
    };

    const contentHtml = renderMarkdownToHtml(notesText);

    // Add content
    const contentDiv = document.createElement("div");
    contentDiv.innerHTML = contentHtml;
    pdfContainer.appendChild(contentDiv);

    // Add diagram if available
    if (diagramUrl) {
      const diagramDiv = document.createElement("div");
      diagramDiv.style.cssText = `
        margin-top: 30px;
        page-break-inside: avoid;
      `;
      diagramDiv.innerHTML = `
        <h2 style="font-size: 32px; color: #7c3aed; margin: 0 0 15px 0; font-weight: 600; font-family: 'Caveat', cursive;">📊 Diagram</h2>
        <img src="${diagramUrl}" alt="Diagram" crossorigin="anonymous" style="width: 100%; max-width: 100%; border-radius: 12px; border: 2px solid #e2e8f0; box-shadow: 0 4px 12px rgba(0,0,0,0.1);" />
      `;
      pdfContainer.appendChild(diagramDiv);
    }

    // Add footer
    const footerDiv = document.createElement("div");
    footerDiv.style.cssText = `
      margin-top: 30px;
      padding-top: 15px;
      border-top: 2px solid #e2e8f0;
      text-align: center;
      font-size: 16px;
      color: #94a3b8;
    `;
    footerDiv.innerHTML = `<p style="margin: 0; font-family: 'Caveat', cursive;">✨ Generated by Lisa AI Assistant • Made with ❤️ for learning</p>`;
    pdfContainer.appendChild(footerDiv);

    // Add to document
    document.body.appendChild(pdfContainer);

    // Wait for rendering
    await new Promise((resolve) => setTimeout(resolve, 800));

    // Capture with html2canvas
    console.log("Capturing canvas...");
    let canvas: HTMLCanvasElement;
    try {
      canvas = await html2canvas(pdfContainer, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#fffdf7",
        logging: false,
        imageTimeout: 0,
        windowWidth: pdfContainer.scrollWidth,
        windowHeight: pdfContainer.scrollHeight,
        scrollX: 0,
        scrollY: 0,
        foreignObjectRendering: true,
      });
    } catch (canvasError) {
      console.error("Canvas capture error:", canvasError);
      cleanupContainer(pdfContainer);
      throw canvasError;
    }

    // Remove the container after capture
    cleanupContainer(pdfContainer);

    if (canvas.width === 0 || canvas.height === 0) {
      throw new Error("Canvas dimensions are zero - content not captured");
    }

    console.log("Canvas captured:", canvas.width, "x", canvas.height);

    // Create PDF
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    const margin = 10;
    const headerH = 12;
    const footerH = 10;
    const availableHeight = pdfHeight - margin * 2 - headerH - footerH;
    const imgWidth = pdfWidth - margin * 2;
    // Calculate the height of each page slice in canvas pixels
    const sliceHeight = Math.round((imgWidth * availableHeight) / (pdfWidth * (canvas.width / canvas.height)) * (canvas.height / availableHeight));
    // Simpler approach: calculate based on aspect ratio
    const canvasAspect = canvas.width / canvas.height;
    const pageAspect = imgWidth / availableHeight;
    const actualSliceHeight = Math.round(availableHeight / (imgWidth / canvas.width));

    const totalPages = Math.ceil(canvas.height / actualSliceHeight);
    console.log(`Total pages: ${totalPages}, slice height: ${actualSliceHeight}`);

    let currentY = 0;
    let pageNum = 1;

    while (currentY < canvas.height) {
      // Create a temporary canvas for this page
      const pageSlice = document.createElement("canvas");
      const remainingHeight = canvas.height - currentY;
      const thisPageHeight = Math.min(actualSliceHeight, remainingHeight);
      
      pageSlice.width = canvas.width;
      pageSlice.height = thisPageHeight;
      
      const ctx = pageSlice.getContext("2d");
      if (!ctx) throw new Error("Cannot get canvas context");

      ctx.fillStyle = "#fffdf7";
      ctx.fillRect(0, 0, pageSlice.width, pageSlice.height);
      
      ctx.drawImage(
        canvas,
        0, currentY, canvas.width, thisPageHeight,
        0, 0, pageSlice.width, pageSlice.height
      );

      const imgData = pageSlice.toDataURL("image/jpeg", 0.95);

      if (pageNum > 1) {
        pdf.addPage();
      }

      // Add page header
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(120, 120, 120);
      pdf.text("Lisa AI Study Notes", margin, margin + 3);

      // Calculate actual image height for this page
      const imgHeight = (imgWidth * thisPageHeight) / canvas.width;

      // Add the image
      pdf.addImage(
        imgData,
        "JPEG",
        margin,
        margin + headerH,
        imgWidth,
        imgHeight
      );

      // Add page footer
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Page ${pageNum} of ${totalPages}`,
        pdfWidth - margin,
        pdfHeight - margin + 3,
        { align: "right" }
      );

      currentY += actualSliceHeight;
      pageNum++;
    }

    // Save PDF
    const fileName = `Study_Notes_${new Date().toISOString().slice(0, 10)}.pdf`;
    pdf.save(fileName);
    console.log("PDF saved successfully!");

  } catch (err) {
    console.error("PDF generation error:", err);

    // Fallback: Text-only PDF with better formatting
    try {
      console.log("Using text fallback...");
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pdfWidth - margin * 2;

      // Title
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(20);
      pdf.setTextColor(30, 58, 138);
      pdf.text("📖 Study Notes", margin, 25);

      // Date
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);
      pdf.setTextColor(100, 116, 138);
      pdf.text(new Date().toLocaleDateString("en-IN"), pdfWidth - margin, 25, { align: "right" });

      // Content with multi-page support
      pdf.setFontSize(11);
      pdf.setTextColor(30, 41, 59);
      const lines = pdf.splitTextToSize(notesText, contentWidth);
      
      let y = 35;
      const lineHeight = 6;
      let pageNum = 1;
      const maxPages = Math.ceil(lines.length / ((pdfHeight - margin * 2) / lineHeight));

      for (let i = 0; i < lines.length; i++) {
        if (y > pdfHeight - margin - 10) {
          // Add page number
          pdf.setFontSize(8);
          pdf.setTextColor(150, 150, 150);
          pdf.text(`Page ${pageNum} of ${maxPages}`, pdfWidth - margin, pdfHeight - margin + 3, { align: "right" });
          
          pdf.addPage();
          pageNum++;
          y = margin;
        }
        pdf.text(lines[i], margin, y);
        y += lineHeight;
      }

      // Final page number
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`Page ${pageNum} of ${maxPages}`, pdfWidth - margin, pdfHeight - margin + 3, { align: "right" });

      const fileName = `Study_Notes_${new Date().toISOString().slice(0, 10)}.pdf`;
      pdf.save(fileName);
      console.log("Fallback PDF saved!");

    } catch (fbErr) {
      console.error("Fallback failed:", fbErr);
      alert("PDF generation failed. Please try again.");
    }
  }
};